/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param title 
 * @param createdAt 
 * @param description 
 * @param ingredients 
 * @param instructions 
 * @param calories 
 * @param category 
 */


data class RecipeResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    @field:JsonProperty("title")
    val title: kotlin.String,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,

    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("ingredients")
    val ingredients: kotlin.String? = null,

    @field:JsonProperty("instructions")
    val instructions: kotlin.String? = null,

    @field:JsonProperty("calories")
    val calories: kotlin.Int? = null,

    @field:JsonProperty("category")
    val category: kotlin.String? = null

)

