/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param title Recipe title
 * @param description Short description of the recipe
 * @param ingredients Ingredients list (free text or structured string)
 * @param instructions Preparation steps
 * @param calories Approximate calories per serving
 * @param category Recipe category (e.g. BREAKFAST, LUNCH, DINNER, SNACK)
 */


data class RecipeRequest (

    /* Recipe title */
    @field:JsonProperty("title")
    val title: kotlin.String,

    /* Short description of the recipe */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Ingredients list (free text or structured string) */
    @field:JsonProperty("ingredients")
    val ingredients: kotlin.String? = null,

    /* Preparation steps */
    @field:JsonProperty("instructions")
    val instructions: kotlin.String? = null,

    /* Approximate calories per serving */
    @field:JsonProperty("calories")
    val calories: kotlin.Int? = null,

    /* Recipe category (e.g. BREAKFAST, LUNCH, DINNER, SNACK) */
    @field:JsonProperty("category")
    val category: kotlin.String? = null

)

