/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param patientId 
 * @param patientFullName 
 * @param specialistId 
 * @param specialistFullName 
 * @param specialistRole 
 * @param scheduledAt 
 * @param serviceType 
 * @param status 
 * @param hasReport 
 * @param price 
 * @param createdAt 
 * @param notes 
 * @param areaId 
 * @param areaName 
 */


data class AppointmentResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    @field:JsonProperty("patientFullName")
    val patientFullName: kotlin.String,

    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    @field:JsonProperty("specialistFullName")
    val specialistFullName: kotlin.String,

    @field:JsonProperty("specialistRole")
    val specialistRole: kotlin.String,

    @field:JsonProperty("scheduledAt")
    val scheduledAt: java.time.OffsetDateTime,

    @field:JsonProperty("serviceType")
    val serviceType: kotlin.String,

    @field:JsonProperty("status")
    val status: kotlin.String,

    @field:JsonProperty("hasReport")
    val hasReport: kotlin.Boolean,

    @field:JsonProperty("price")
    val price: kotlin.Double,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,

    @field:JsonProperty("notes")
    val notes: kotlin.String? = null,

    @field:JsonProperty("areaId")
    val areaId: kotlin.Long? = null,

    @field:JsonProperty("areaName")
    val areaName: kotlin.String? = null

)

