/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param patientId 
 * @param specialistId 
 * @param scheduledAt 
 * @param serviceType 
 * @param notes 
 * @param price 
 */


data class AppointmentRequest (

    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    @field:JsonProperty("scheduledAt")
    val scheduledAt: java.time.OffsetDateTime,

    @field:JsonProperty("serviceType")
    val serviceType: kotlin.String,

    @field:JsonProperty("notes")
    val notes: kotlin.String? = null,

    @field:JsonProperty("price")
    val price: kotlin.Double? = 0.0

)

