/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param patientId 
 * @param patientFullName Full name of the patient
 * @param specialistId 
 * @param specialistFullName Full name of the specialist
 * @param specialistSpecialization Specialization of the specialist
 * @param scheduledAt 
 * @param visitType 
 * @param status Appointment status (BOOKED, COMPLETED, CANCELLED)
 * @param hasReport Whether a clinical report has been filed for this appointment
 * @param createdAt 
 * @param notes 
 */


data class AppointmentResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    /* Full name of the patient */
    @field:JsonProperty("patientFullName")
    val patientFullName: kotlin.String,

    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    /* Full name of the specialist */
    @field:JsonProperty("specialistFullName")
    val specialistFullName: kotlin.String,

    /* Specialization of the specialist */
    @field:JsonProperty("specialistSpecialization")
    val specialistSpecialization: kotlin.String,

    @field:JsonProperty("scheduledAt")
    val scheduledAt: java.time.OffsetDateTime,

    @field:JsonProperty("visitType")
    val visitType: kotlin.String,

    /* Appointment status (BOOKED, COMPLETED, CANCELLED) */
    @field:JsonProperty("status")
    val status: kotlin.String,

    /* Whether a clinical report has been filed for this appointment */
    @field:JsonProperty("hasReport")
    val hasReport: kotlin.Boolean,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,

    @field:JsonProperty("notes")
    val notes: kotlin.String? = null

)

