/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param patientId ID of the patient
 * @param specialistId ID of the specialist
 * @param scheduledAt Scheduled date and time of the appointment
 * @param visitType Type of medical visit (e.g. CARDIOLOGY, DERMATOLOGY, GENERAL)
 * @param notes Optional notes for the appointment
 */


data class AppointmentRequest (

    /* ID of the patient */
    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    /* ID of the specialist */
    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    /* Scheduled date and time of the appointment */
    @field:JsonProperty("scheduledAt")
    val scheduledAt: java.time.OffsetDateTime,

    /* Type of medical visit (e.g. CARDIOLOGY, DERMATOLOGY, GENERAL) */
    @field:JsonProperty("visitType")
    val visitType: kotlin.String,

    /* Optional notes for the appointment */
    @field:JsonProperty("notes")
    val notes: kotlin.String? = null

)

