/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param appointmentId 
 * @param patientFullName Full name of the patient
 * @param specialistFullName Full name of the specialist
 * @param visitType Service type of the linked fitness appointment
 * @param scheduledAt Date and time of the linked appointment
 * @param issuedDate Date the report was issued
 * @param diagnosis 
 * @param createdAt 
 * @param prescription 
 * @param specialistNotes 
 */


data class ReportResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    @field:JsonProperty("appointmentId")
    val appointmentId: kotlin.Long,

    /* Full name of the patient */
    @field:JsonProperty("patientFullName")
    val patientFullName: kotlin.String,

    /* Full name of the specialist */
    @field:JsonProperty("specialistFullName")
    val specialistFullName: kotlin.String,

    /* Service type of the linked fitness appointment */
    @field:JsonProperty("visitType")
    val visitType: kotlin.String,

    /* Date and time of the linked appointment */
    @field:JsonProperty("scheduledAt")
    val scheduledAt: java.time.OffsetDateTime,

    /* Date the report was issued */
    @field:JsonProperty("issuedDate")
    val issuedDate: java.time.LocalDate,

    @field:JsonProperty("diagnosis")
    val diagnosis: kotlin.String,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,

    @field:JsonProperty("prescription")
    val prescription: kotlin.String? = null,

    @field:JsonProperty("specialistNotes")
    val specialistNotes: kotlin.String? = null

)

