/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param appointmentId ID of the appointment this report refers to
 * @param diagnosis Clinical diagnosis
 * @param prescription Prescription or treatment plan
 * @param specialistNotes Additional notes from the specialist
 */


data class ReportRequest (

    /* ID of the appointment this report refers to */
    @field:JsonProperty("appointmentId")
    val appointmentId: kotlin.Long,

    /* Clinical diagnosis */
    @field:JsonProperty("diagnosis")
    val diagnosis: kotlin.String,

    /* Prescription or treatment plan */
    @field:JsonProperty("prescription")
    val prescription: kotlin.String? = null,

    /* Additional notes from the specialist */
    @field:JsonProperty("specialistNotes")
    val specialistNotes: kotlin.String? = null

)

