/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param status New appointment status (e.g. BOOKED, COMPLETED, CANCELLED)
 */


data class FitnessAppointmentStatusRequest (

    /* New appointment status (e.g. BOOKED, COMPLETED, CANCELLED) */
    @field:JsonProperty("status")
    val status: kotlin.String

)

