/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param patientId ID of the patient
 * @param specialistId ID of the specialist (trainer)
 * @param scheduledAt Scheduled date and time of the fitness appointment
 * @param serviceType Type of fitness service (e.g. PERSONAL_TRAINING, YOGA, PILATES)
 * @param notes Optional notes for the appointment
 */


data class FitnessAppointmentRequest (

    /* ID of the patient */
    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    /* ID of the specialist (trainer) */
    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    /* Scheduled date and time of the fitness appointment */
    @field:JsonProperty("scheduledAt")
    val scheduledAt: java.time.OffsetDateTime,

    /* Type of fitness service (e.g. PERSONAL_TRAINING, YOGA, PILATES) */
    @field:JsonProperty("serviceType")
    val serviceType: kotlin.String,

    /* Optional notes for the appointment */
    @field:JsonProperty("notes")
    val notes: kotlin.String? = null

)

