/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param patientId 
 * @param patientFullName Full name of the patient
 * @param specialistId 
 * @param specialistFullName Full name of the specialist
 * @param specialistRole Role of the specialist (e.g. TRAINER, NUTRITIONIST)
 * @param scheduledAt 
 * @param serviceType 
 * @param status Appointment status (BOOKED, COMPLETED, CANCELLED)
 * @param createdAt 
 * @param notes 
 */


data class FitnessAppointmentResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    /* Full name of the patient */
    @field:JsonProperty("patientFullName")
    val patientFullName: kotlin.String,

    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    /* Full name of the specialist */
    @field:JsonProperty("specialistFullName")
    val specialistFullName: kotlin.String,

    /* Role of the specialist (e.g. TRAINER, NUTRITIONIST) */
    @field:JsonProperty("specialistRole")
    val specialistRole: kotlin.String,

    @field:JsonProperty("scheduledAt")
    val scheduledAt: java.time.OffsetDateTime,

    @field:JsonProperty("serviceType")
    val serviceType: kotlin.String,

    /* Appointment status (BOOKED, COMPLETED, CANCELLED) */
    @field:JsonProperty("status")
    val status: kotlin.String,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,

    @field:JsonProperty("notes")
    val notes: kotlin.String? = null

)

