/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param firstName Patient's first name
 * @param lastName Patient's last name
 * @param fiscalCode Italian fiscal code (16 characters, e.g. RSSMRA85T10A562S)
 * @param birthDate Patient's birth date
 * @param email Patient's email address
 * @param phone Patient's phone number
 */


data class PatientRequest (

    /* Patient's first name */
    @field:JsonProperty("firstName")
    val firstName: kotlin.String,

    /* Patient's last name */
    @field:JsonProperty("lastName")
    val lastName: kotlin.String,

    /* Italian fiscal code (16 characters, e.g. RSSMRA85T10A562S) */
    @field:JsonProperty("fiscalCode")
    val fiscalCode: kotlin.String,

    /* Patient's birth date */
    @field:JsonProperty("birthDate")
    val birthDate: java.time.LocalDate,

    /* Patient's email address */
    @field:JsonProperty("email")
    val email: kotlin.String,

    /* Patient's phone number */
    @field:JsonProperty("phone")
    val phone: kotlin.String? = null

)

