/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param firstName 
 * @param lastName 
 * @param fiscalCode Italian fiscal code
 * @param birthDate 
 * @param email 
 * @param createdAt 
 * @param phone 
 */


data class PatientResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    @field:JsonProperty("firstName")
    val firstName: kotlin.String,

    @field:JsonProperty("lastName")
    val lastName: kotlin.String,

    /* Italian fiscal code */
    @field:JsonProperty("fiscalCode")
    val fiscalCode: kotlin.String,

    @field:JsonProperty("birthDate")
    val birthDate: java.time.LocalDate,

    @field:JsonProperty("email")
    val email: kotlin.String,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,

    @field:JsonProperty("phone")
    val phone: kotlin.String? = null

)

