/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param timestamp 
 * @param status 
 * @param error 
 * @param message 
 * @param path 
 */


data class ErrorResponse (

    @field:JsonProperty("timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @field:JsonProperty("status")
    val status: kotlin.Int? = null,

    @field:JsonProperty("error")
    val error: kotlin.String? = null,

    @field:JsonProperty("message")
    val message: kotlin.String? = null,

    @field:JsonProperty("path")
    val path: kotlin.String? = null

)

