/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param patientId ID of the patient
 * @param specialistId ID of the assigned specialist
 * @param title 
 * @param description 
 * @param weeks 
 * @param sessionsPerWeek 
 * @param active 
 */


data class TrainingPlanRequest (

    /* ID of the patient */
    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    /* ID of the assigned specialist */
    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    @field:JsonProperty("title")
    val title: kotlin.String,

    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("weeks")
    val weeks: kotlin.Int? = null,

    @field:JsonProperty("sessionsPerWeek")
    val sessionsPerWeek: kotlin.Int? = null,

    @field:JsonProperty("active")
    val active: kotlin.Boolean? = true

)

