/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param patientId 
 * @param patientFullName 
 * @param specialistId 
 * @param specialistFullName 
 * @param title 
 * @param description 
 * @param weeks 
 * @param sessionsPerWeek 
 * @param active 
 * @param createdAt 
 */


data class TrainingPlanResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long? = null,

    @field:JsonProperty("patientId")
    val patientId: kotlin.Long? = null,

    @field:JsonProperty("patientFullName")
    val patientFullName: kotlin.String? = null,

    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long? = null,

    @field:JsonProperty("specialistFullName")
    val specialistFullName: kotlin.String? = null,

    @field:JsonProperty("title")
    val title: kotlin.String? = null,

    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("weeks")
    val weeks: kotlin.Int? = null,

    @field:JsonProperty("sessionsPerWeek")
    val sessionsPerWeek: kotlin.Int? = null,

    @field:JsonProperty("active")
    val active: kotlin.Boolean? = null,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime? = null

)

