/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ignore.api

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.clinic.model.GlycemiaClassificationRulesResponse
import com.clinic.model.GlycemiaMeasurementRequest
import com.clinic.model.GlycemiaMeasurementResponse
import com.clinic.model.ValidationErrorResponse

import com.fasterxml.jackson.annotation.JsonProperty

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class DefaultApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8080")
        }
    }

    /**
     * Record a new glycemia measurement
     * Saves a new blood glucose measurement for a patient.
     * @param glycemiaMeasurementRequest 
     * @return GlycemiaMeasurementResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createGlycemiaMeasurement(glycemiaMeasurementRequest: GlycemiaMeasurementRequest) : GlycemiaMeasurementResponse {
        val localVarResponse = createGlycemiaMeasurementWithHttpInfo(glycemiaMeasurementRequest = glycemiaMeasurementRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GlycemiaMeasurementResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Record a new glycemia measurement
     * Saves a new blood glucose measurement for a patient.
     * @param glycemiaMeasurementRequest 
     * @return ApiResponse<GlycemiaMeasurementResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createGlycemiaMeasurementWithHttpInfo(glycemiaMeasurementRequest: GlycemiaMeasurementRequest) : ApiResponse<GlycemiaMeasurementResponse?> {
        val localVariableConfig = createGlycemiaMeasurementRequestConfig(glycemiaMeasurementRequest = glycemiaMeasurementRequest)

        return request<GlycemiaMeasurementRequest, GlycemiaMeasurementResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createGlycemiaMeasurement
     *
     * @param glycemiaMeasurementRequest 
     * @return RequestConfig
     */
    fun createGlycemiaMeasurementRequestConfig(glycemiaMeasurementRequest: GlycemiaMeasurementRequest) : RequestConfig<GlycemiaMeasurementRequest> {
        val localVariableBody = glycemiaMeasurementRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/glycemia-measurements",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Delete a glycemia measurement
     * 
     * @param id Measurement ID
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteGlycemiaMeasurement(id: kotlin.Long) : Unit {
        val localVarResponse = deleteGlycemiaMeasurementWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Delete a glycemia measurement
     * 
     * @param id Measurement ID
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteGlycemiaMeasurementWithHttpInfo(id: kotlin.Long) : ApiResponse<Unit?> {
        val localVariableConfig = deleteGlycemiaMeasurementRequestConfig(id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteGlycemiaMeasurement
     *
     * @param id Measurement ID
     * @return RequestConfig
     */
    fun deleteGlycemiaMeasurementRequestConfig(id: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/glycemia-measurements/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * List glycemia measurements
     * Returns all measurements ordered by date desc. Optionally filter by patientId.
     * @param patientId Filter by patient ID (optional)
     * @return kotlin.collections.List<GlycemiaMeasurementResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun findAllGlycemiaMeasurements(patientId: kotlin.Long? = null) : kotlin.collections.List<GlycemiaMeasurementResponse> {
        val localVarResponse = findAllGlycemiaMeasurementsWithHttpInfo(patientId = patientId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<GlycemiaMeasurementResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List glycemia measurements
     * Returns all measurements ordered by date desc. Optionally filter by patientId.
     * @param patientId Filter by patient ID (optional)
     * @return ApiResponse<kotlin.collections.List<GlycemiaMeasurementResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun findAllGlycemiaMeasurementsWithHttpInfo(patientId: kotlin.Long?) : ApiResponse<kotlin.collections.List<GlycemiaMeasurementResponse>?> {
        val localVariableConfig = findAllGlycemiaMeasurementsRequestConfig(patientId = patientId)

        return request<Unit, kotlin.collections.List<GlycemiaMeasurementResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation findAllGlycemiaMeasurements
     *
     * @param patientId Filter by patient ID (optional)
     * @return RequestConfig
     */
    fun findAllGlycemiaMeasurementsRequestConfig(patientId: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (patientId != null) {
                    put("patientId", listOf(patientId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/glycemia-measurements",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get ADA/WHO glycemia classification rules
     * Returns the complete classification thresholds for each measurement context. Use this endpoint to dynamically render classification legends in the UI instead of hard-coding them on the frontend. 
     * @return GlycemiaClassificationRulesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getGlycemiaClassificationRules() : GlycemiaClassificationRulesResponse {
        val localVarResponse = getGlycemiaClassificationRulesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GlycemiaClassificationRulesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get ADA/WHO glycemia classification rules
     * Returns the complete classification thresholds for each measurement context. Use this endpoint to dynamically render classification legends in the UI instead of hard-coding them on the frontend. 
     * @return ApiResponse<GlycemiaClassificationRulesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getGlycemiaClassificationRulesWithHttpInfo() : ApiResponse<GlycemiaClassificationRulesResponse?> {
        val localVariableConfig = getGlycemiaClassificationRulesRequestConfig()

        return request<Unit, GlycemiaClassificationRulesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getGlycemiaClassificationRules
     *
     * @return RequestConfig
     */
    fun getGlycemiaClassificationRulesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/glycemia-measurements/classification-rules",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get a glycemia measurement by ID
     * 
     * @param id Measurement ID
     * @return GlycemiaMeasurementResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getGlycemiaMeasurementById(id: kotlin.Long) : GlycemiaMeasurementResponse {
        val localVarResponse = getGlycemiaMeasurementByIdWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GlycemiaMeasurementResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get a glycemia measurement by ID
     * 
     * @param id Measurement ID
     * @return ApiResponse<GlycemiaMeasurementResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getGlycemiaMeasurementByIdWithHttpInfo(id: kotlin.Long) : ApiResponse<GlycemiaMeasurementResponse?> {
        val localVariableConfig = getGlycemiaMeasurementByIdRequestConfig(id = id)

        return request<Unit, GlycemiaMeasurementResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getGlycemiaMeasurementById
     *
     * @param id Measurement ID
     * @return RequestConfig
     */
    fun getGlycemiaMeasurementByIdRequestConfig(id: kotlin.Long) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/glycemia-measurements/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Update a glycemia measurement
     * 
     * @param id Measurement ID
     * @param glycemiaMeasurementRequest 
     * @return GlycemiaMeasurementResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateGlycemiaMeasurement(id: kotlin.Long, glycemiaMeasurementRequest: GlycemiaMeasurementRequest) : GlycemiaMeasurementResponse {
        val localVarResponse = updateGlycemiaMeasurementWithHttpInfo(id = id, glycemiaMeasurementRequest = glycemiaMeasurementRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GlycemiaMeasurementResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Update a glycemia measurement
     * 
     * @param id Measurement ID
     * @param glycemiaMeasurementRequest 
     * @return ApiResponse<GlycemiaMeasurementResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateGlycemiaMeasurementWithHttpInfo(id: kotlin.Long, glycemiaMeasurementRequest: GlycemiaMeasurementRequest) : ApiResponse<GlycemiaMeasurementResponse?> {
        val localVariableConfig = updateGlycemiaMeasurementRequestConfig(id = id, glycemiaMeasurementRequest = glycemiaMeasurementRequest)

        return request<GlycemiaMeasurementRequest, GlycemiaMeasurementResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateGlycemiaMeasurement
     *
     * @param id Measurement ID
     * @param glycemiaMeasurementRequest 
     * @return RequestConfig
     */
    fun updateGlycemiaMeasurementRequestConfig(id: kotlin.Long, glycemiaMeasurementRequest: GlycemiaMeasurementRequest) : RequestConfig<GlycemiaMeasurementRequest> {
        val localVariableBody = glycemiaMeasurementRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/glycemia-measurements/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
