-- V10 H2: Create fitness_appointment table
CREATE TABLE fitness_appointment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id   BIGINT       NOT NULL REFERENCES patient(id),
    trainer_id   BIGINT       NOT NULL REFERENCES specialist(id),
    scheduled_at TIMESTAMP    NOT NULL,
    service_type VARCHAR(200) NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'BOOKED',
    notes        TEXT,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fitness_appt_patient_id    ON fitness_appointment(patient_id);
CREATE INDEX idx_fitness_appt_trainer_id   ON fitness_appointment(trainer_id);
CREATE INDEX idx_fitness_appt_scheduled_at ON fitness_appointment(scheduled_at);
CREATE INDEX idx_fitness_appt_status       ON fitness_appointment(status);
