-- V8 H2: Create diet_plan table
CREATE TABLE diet_plan (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id     BIGINT       NOT NULL REFERENCES patient(id),
    trainer_id     BIGINT       NOT NULL REFERENCES specialist(id),
    title          VARCHAR(255) NOT NULL,
    description    TEXT,
    calories       INT,
    duration_weeks INT,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_diet_plan_patient_id  ON diet_plan(patient_id);
CREATE INDEX idx_diet_plan_trainer_id ON diet_plan(trainer_id);
CREATE INDEX idx_diet_plan_active     ON diet_plan(active);
