/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Risposta di errore generica per gli endpoint di autenticazione
 *
 * @param message Descrizione dell'errore
 * @param success 
 */


data class AuthErrorResponse (

    /* Descrizione dell'errore */
    @field:JsonProperty("message")
    val message: kotlin.String? = null,

    @field:JsonProperty("success")
    val success: kotlin.Boolean? = null

)

