/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Credenziali di accesso
 *
 * @param username Nome utente
 * @param password Password
 */


data class LoginRequest (

    /* Nome utente */
    @field:JsonProperty("username")
    val username: kotlin.String,

    /* Password */
    @field:JsonProperty("password")
    val password: kotlin.String

)

