/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Risposta alla registrazione andata a buon fine
 *
 * @param message Messaggio descrittivo dell'esito
 * @param success Indica se la registrazione è avvenuta con successo
 * @param username Username dell'account creato
 * @param email Email dell'account creato
 * @param patientId ID del profilo paziente creato
 */


data class RegisterResponse (

    /* Messaggio descrittivo dell'esito */
    @field:JsonProperty("message")
    val message: kotlin.String,

    /* Indica se la registrazione è avvenuta con successo */
    @field:JsonProperty("success")
    val success: kotlin.Boolean,

    /* Username dell'account creato */
    @field:JsonProperty("username")
    val username: kotlin.String,

    /* Email dell'account creato */
    @field:JsonProperty("email")
    val email: kotlin.String,

    /* ID del profilo paziente creato */
    @field:JsonProperty("patientId")
    val patientId: kotlin.Long

)

