/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Dati necessari per registrare un nuovo paziente e creare il suo account
 *
 * @param firstName Nome del paziente
 * @param lastName Cognome del paziente
 * @param fiscalCode Codice fiscale italiano (16 caratteri, solo maiuscole)
 * @param birthDate Data di nascita (formato ISO 8601 yyyy-MM-dd)
 * @param email Indirizzo email (deve essere univoco)
 * @param username Nome utente per l'accesso (deve essere univoco)
 * @param password Password per l'accesso (minimo 8 caratteri)
 * @param phone Numero di telefono (opzionale)
 */


data class RegisterRequest (

    /* Nome del paziente */
    @field:JsonProperty("firstName")
    val firstName: kotlin.String,

    /* Cognome del paziente */
    @field:JsonProperty("lastName")
    val lastName: kotlin.String,

    /* Codice fiscale italiano (16 caratteri, solo maiuscole) */
    @field:JsonProperty("fiscalCode")
    val fiscalCode: kotlin.String,

    /* Data di nascita (formato ISO 8601 yyyy-MM-dd) */
    @field:JsonProperty("birthDate")
    val birthDate: java.time.LocalDate,

    /* Indirizzo email (deve essere univoco) */
    @field:JsonProperty("email")
    val email: kotlin.String,

    /* Nome utente per l'accesso (deve essere univoco) */
    @field:JsonProperty("username")
    val username: kotlin.String,

    /* Password per l'accesso (minimo 8 caratteri) */
    @field:JsonProperty("password")
    val password: kotlin.String,

    /* Numero di telefono (opzionale) */
    @field:JsonProperty("phone")
    val phone: kotlin.String? = null

)

