/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param valid true se il token è valido
 * @param username Username estratto dal token (vuoto se non valido)
 * @param message Messaggio descrittivo
 */


data class TokenValidationResponse (

    /* true se il token è valido */
    @field:JsonProperty("valid")
    val valid: kotlin.Boolean,

    /* Username estratto dal token (vuoto se non valido) */
    @field:JsonProperty("username")
    val username: kotlin.String,

    /* Messaggio descrittivo */
    @field:JsonProperty("message")
    val message: kotlin.String

)

