/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param firstName 
 * @param lastName 
 * @param role 
 * @param email 
 * @param bio 
 */


data class SpecialistRequest (

    @field:JsonProperty("firstName")
    val firstName: kotlin.String,

    @field:JsonProperty("lastName")
    val lastName: kotlin.String,

    @field:JsonProperty("role")
    val role: kotlin.String,

    @field:JsonProperty("email")
    val email: kotlin.String,

    @field:JsonProperty("bio")
    val bio: kotlin.String? = null

)

