/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param patientId ID of the patient
 * @param specialistId ID of the specialist (nutritionist) assigning the plan
 * @param title Title of the diet plan
 * @param description Optional description of the plan
 * @param calories Daily calorie target (500–5000)
 * @param durationWeeks Duration of the plan in weeks (1–52)
 * @param active Whether the plan is currently active
 */


data class DietPlanRequest (

    /* ID of the patient */
    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    /* ID of the specialist (nutritionist) assigning the plan */
    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    /* Title of the diet plan */
    @field:JsonProperty("title")
    val title: kotlin.String,

    /* Optional description of the plan */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Daily calorie target (500–5000) */
    @field:JsonProperty("calories")
    val calories: kotlin.Int? = null,

    /* Duration of the plan in weeks (1–52) */
    @field:JsonProperty("durationWeeks")
    val durationWeeks: kotlin.Int? = null,

    /* Whether the plan is currently active */
    @field:JsonProperty("active")
    val active: kotlin.Boolean? = true

)

