/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param patientId 
 * @param specialistId 
 * @param patientFirstName 
 * @param patientLastName 
 * @param specialistFirstName 
 * @param specialistLastName 
 * @param title 
 * @param active 
 * @param createdAt 
 * @param updatedAt 
 * @param description 
 * @param calories 
 * @param durationWeeks 
 */


data class DietPlanResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    @field:JsonProperty("patientFirstName")
    val patientFirstName: kotlin.String,

    @field:JsonProperty("patientLastName")
    val patientLastName: kotlin.String,

    @field:JsonProperty("specialistFirstName")
    val specialistFirstName: kotlin.String,

    @field:JsonProperty("specialistLastName")
    val specialistLastName: kotlin.String,

    @field:JsonProperty("title")
    val title: kotlin.String,

    @field:JsonProperty("active")
    val active: kotlin.Boolean,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,

    @field:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("calories")
    val calories: kotlin.Int? = null,

    @field:JsonProperty("durationWeeks")
    val durationWeeks: kotlin.Int? = null

)

