/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param patientId ID of the patient
 * @param specialistId ID of the specialist recording the measurement
 * @param measuredAt Date and time of the measurement
 * @param valueMgDl Blood glucose value in mg/dL (range 20–600)
 * @param context Measurement context
 * @param notes Optional clinical notes
 */


data class GlycemiaMeasurementRequest (

    /* ID of the patient */
    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    /* ID of the specialist recording the measurement */
    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    /* Date and time of the measurement */
    @field:JsonProperty("measuredAt")
    val measuredAt: java.time.OffsetDateTime,

    /* Blood glucose value in mg/dL (range 20–600) */
    @field:JsonProperty("valueMgDl")
    val valueMgDl: kotlin.Int,

    /* Measurement context */
    @field:JsonProperty("context")
    val context: GlycemiaMeasurementRequest.Context,

    /* Optional clinical notes */
    @field:JsonProperty("notes")
    val notes: kotlin.String? = null

) {

    /**
     * Measurement context
     *
     * Values: A_DIGIUNO,POST_PASTO_1H,POST_PASTO_2H
     */
    enum class Context(val value: kotlin.String) {
        @JsonProperty(value = "A_DIGIUNO") A_DIGIUNO("A_DIGIUNO"),
        @JsonProperty(value = "POST_PASTO_1H") POST_PASTO_1H("POST_PASTO_1H"),
        @JsonProperty(value = "POST_PASTO_2H") POST_PASTO_2H("POST_PASTO_2H");
    }
}

