/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param patientId 
 * @param patientFirstName 
 * @param patientLastName 
 * @param specialistId 
 * @param specialistFirstName 
 * @param specialistLastName 
 * @param measuredAt 
 * @param valueMgDl Blood glucose value in mg/dL
 * @param context Measurement context
 * @param classification ADA/WHO classification derived from context and value
 * @param createdAt 
 * @param updatedAt 
 * @param notes 
 */


data class GlycemiaMeasurementResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    @field:JsonProperty("patientId")
    val patientId: kotlin.Long,

    @field:JsonProperty("patientFirstName")
    val patientFirstName: kotlin.String,

    @field:JsonProperty("patientLastName")
    val patientLastName: kotlin.String,

    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    @field:JsonProperty("specialistFirstName")
    val specialistFirstName: kotlin.String,

    @field:JsonProperty("specialistLastName")
    val specialistLastName: kotlin.String,

    @field:JsonProperty("measuredAt")
    val measuredAt: java.time.OffsetDateTime,

    /* Blood glucose value in mg/dL */
    @field:JsonProperty("valueMgDl")
    val valueMgDl: kotlin.Int,

    /* Measurement context */
    @field:JsonProperty("context")
    val context: GlycemiaMeasurementResponse.Context,

    /* ADA/WHO classification derived from context and value */
    @field:JsonProperty("classification")
    val classification: GlycemiaMeasurementResponse.Classification,

    @field:JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,

    @field:JsonProperty("updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @field:JsonProperty("notes")
    val notes: kotlin.String? = null

) {

    /**
     * Measurement context
     *
     * Values: A_DIGIUNO,POST_PASTO_1H,POST_PASTO_2H
     */
    enum class Context(val value: kotlin.String) {
        @JsonProperty(value = "A_DIGIUNO") A_DIGIUNO("A_DIGIUNO"),
        @JsonProperty(value = "POST_PASTO_1H") POST_PASTO_1H("POST_PASTO_1H"),
        @JsonProperty(value = "POST_PASTO_2H") POST_PASTO_2H("POST_PASTO_2H");
    }
    /**
     * ADA/WHO classification derived from context and value
     *
     * Values: NORMALE,ATTENZIONE,ELEVATA
     */
    enum class Classification(val value: kotlin.String) {
        @JsonProperty(value = "NORMALE") NORMALE("NORMALE"),
        @JsonProperty(value = "ATTENZIONE") ATTENZIONE("ATTENZIONE"),
        @JsonProperty(value = "ELEVATA") ELEVATA("ELEVATA");
    }
}

