/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model

import com.clinic.model.GlycemiaThreshold

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param context 
 * @param label Human-readable context label for UI display
 * @param thresholds 
 */


data class GlycemiaContextRules (

    @field:JsonProperty("context")
    val context: GlycemiaContextRules.Context,

    /* Human-readable context label for UI display */
    @field:JsonProperty("label")
    val label: kotlin.String,

    @field:JsonProperty("thresholds")
    val thresholds: kotlin.collections.List<GlycemiaThreshold>

) {

    /**
     * 
     *
     * Values: A_DIGIUNO,POST_PASTO_1H,POST_PASTO_2H
     */
    enum class Context(val value: kotlin.String) {
        @JsonProperty(value = "A_DIGIUNO") A_DIGIUNO("A_DIGIUNO"),
        @JsonProperty(value = "POST_PASTO_1H") POST_PASTO_1H("POST_PASTO_1H"),
        @JsonProperty(value = "POST_PASTO_2H") POST_PASTO_2H("POST_PASTO_2H");
    }
}

