/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param classification 
 * @param label Human-readable threshold label for UI display
 * @param minMgDl Lower bound in mg/dL (null = no lower bound)
 * @param maxMgDl Upper bound in mg/dL (null = no upper bound)
 */


data class GlycemiaThreshold (

    @field:JsonProperty("classification")
    val classification: GlycemiaThreshold.Classification,

    /* Human-readable threshold label for UI display */
    @field:JsonProperty("label")
    val label: kotlin.String,

    /* Lower bound in mg/dL (null = no lower bound) */
    @field:JsonProperty("minMgDl")
    val minMgDl: kotlin.Int? = null,

    /* Upper bound in mg/dL (null = no upper bound) */
    @field:JsonProperty("maxMgDl")
    val maxMgDl: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: NORMALE,ATTENZIONE,ELEVATA
     */
    enum class Classification(val value: kotlin.String) {
        @JsonProperty(value = "NORMALE") NORMALE("NORMALE"),
        @JsonProperty(value = "ATTENZIONE") ATTENZIONE("ATTENZIONE"),
        @JsonProperty(value = "ELEVATA") ELEVATA("ELEVATA");
    }
}

