/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model

import com.clinic.model.GlycemiaContextRules

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param contexts Classification rules for each measurement context
 */


data class GlycemiaClassificationRulesResponse (

    /* Classification rules for each measurement context */
    @field:JsonProperty("contexts")
    val contexts: kotlin.collections.List<GlycemiaContextRules>

)

