/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param status 
 * @param errors 
 */


data class ValidationErrorResponse (

    @field:JsonProperty("status")
    val status: kotlin.Int? = null,

    @field:JsonProperty("errors")
    val errors: kotlin.collections.List<kotlin.String>? = null

)

