/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param service Name of the service offered
 * @param price Price of the service in euros
 * @param specialistId ID of the specialist offering this service
 */


data class ServiceRequest (

    /* Name of the service offered */
    @field:JsonProperty("service")
    val service: kotlin.String,

    /* Price of the service in euros */
    @field:JsonProperty("price")
    val price: kotlin.Double,

    /* ID of the specialist offering this service */
    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long

)

