/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.clinic.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param service Name of the service offered
 * @param price Price of the service in euros
 * @param specialistId ID of the specialist offering this service
 * @param areaId ID of the area this service belongs to
 * @param areaName Name of the area this service belongs to
 */


data class ServiceResponse (

    @field:JsonProperty("id")
    val id: kotlin.Long,

    /* Name of the service offered */
    @field:JsonProperty("service")
    val service: kotlin.String,

    /* Price of the service in euros */
    @field:JsonProperty("price")
    val price: kotlin.Double,

    /* ID of the specialist offering this service */
    @field:JsonProperty("specialistId")
    val specialistId: kotlin.Long,

    /* ID of the area this service belongs to */
    @field:JsonProperty("areaId")
    val areaId: kotlin.Long? = null,

    /* Name of the area this service belongs to */
    @field:JsonProperty("areaName")
    val areaName: kotlin.String? = null

)

